/*
 * KAS KELAS 12.5 — Google Apps Script Web App (JSON API)
 * Admin history is stored independently from Sheet1/layout.
 */

const SHEET_SISWA='Siswa';
const SHEET_PEMBAYARAN='Pembayaran';
const SHEET_PENGELUARAN='Pengeluaran';
const SHEET_PENGATURAN='Pengaturan';
const SHEET_HISTORY_ADMIN='History Admin';
const ADMIN_PIN='125125';

const DEFAULT_STUDENTS=['Alisa Vernanda Pramesti','Annisa Rizki Sakinah','Aqila Misk Maulida','Arba Maulanal Kirom','Asyfa Hesti Azahra','Aydin Tsany Ramada','Azareel Yanna Direndra','Danendra Farraz Afandi','Davina Almira','Devan Ahmad Rahmadi','Farras Syafiq Azri Mahardika','Farrel Andhika Ferdian','Gayatri Putri Cahyani','Hadyan Aulia Akbar','Hafiz Habiburrahman','Kamilah Khanza Kurniaputri','Kayyisah Adhwa Rashanah','Keisya Ananda','Khalisa Kirani','Luqiya Ramizah Alya','Muhammad Yusuf Rasyadan','Nafeeza Aulia Prihartono','Najla Aqmarina Wardoyo','Palguna Satriya Abyasa','Rafindra Fabian Araya','Rahmania Najma Fadhilah','Razha Khazan Al Mahendra','Rihana Putri Yasmin','Rizki Ferdiansyah','Shabirah Zahrah','Suhaila Saliha','Syafira Apriliani','Valya Devina Anshari','Yasmin Nur Shabrina','Yuuki Aisyah Al Arifi','Zarra Alifa Kinanti'];
const ALLOWED_GET_ACTIONS=['getStudentList','getStudentStatus','getTransparencyData','getTransparencyDashboard'];
const ALLOWED_POST_ACTIONS=['login','getAdminDashboard','addPayment','addExpense','updateSettings','addStudent'];

function doGet(e){try{const action=e&&e.parameter&&e.parameter.action;if(!action)return jsonResponse({success:false,error:'Parameter action wajib diisi.'});if(ALLOWED_GET_ACTIONS.indexOf(action)===-1)return jsonResponse({success:false,error:'Action tidak dikenali: '+action});let data;switch(action){case'getStudentList':data=getStudentList();break;case'getStudentStatus':data=getStudentStatus(e.parameter.nama);break;case'getTransparencyData':data=getTransparencyData();break;case'getTransparencyDashboard':data=getTransparencyDashboard();break;}return jsonResponse({success:true,data:data});}catch(err){return jsonResponse({success:false,error:err.message});}}
function doPost(e){try{if(!e||!e.postData||!e.postData.contents)return jsonResponse({success:false,error:'Body request kosong.'});const body=JSON.parse(e.postData.contents);const action=body.action;if(ALLOWED_POST_ACTIONS.indexOf(action)===-1)return jsonResponse({success:false,error:'Action tidak dikenali: '+action});let data;switch(action){case'login':case'getAdminDashboard':data=getAdminDashboard(body.pin);break;case'addPayment':data={message:addPayment(body.pin,body.nama,body.tanggal,body.jumlah,body.keterangan)};break;case'addExpense':data={message:addExpense(body.pin,body.tanggal,body.deskripsi,body.jumlah)};break;case'updateSettings':data={message:updateSettings(body.pin,body.tanggalMulai,body.iuranMingguan,body.saldoAwal)};break;case'addStudent':data={message:addStudent(body.pin,body.nama)};break;}return jsonResponse({success:true,data:data});}catch(err){return jsonResponse({success:false,error:err.message});}}
function jsonResponse(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function getSS(){return SpreadsheetApp.getActiveSpreadsheet();}

function setupSheets(){const ss=getSS();let sh=ss.getSheetByName(SHEET_SISWA);if(!sh)sh=ss.insertSheet(SHEET_SISWA);if(sh.getLastRow()===0){sh.getRange(1,1,1,2).setValues([['No','Nama']]).setFontWeight('bold');sh.getRange(2,1,DEFAULT_STUDENTS.length,2).setValues(DEFAULT_STUDENTS.map((name,i)=>[i+1,name]));sh.setColumnWidths(1,1,50);sh.setColumnWidths(2,1,250);}sh=ss.getSheetByName(SHEET_PEMBAYARAN);if(!sh)sh=ss.insertSheet(SHEET_PEMBAYARAN);if(sh.getLastRow()===0)sh.getRange(1,1,1,5).setValues([['Timestamp','Nama','Tanggal Bayar','Jumlah (Rp)','Keterangan']]).setFontWeight('bold');sh=ss.getSheetByName(SHEET_PENGELUARAN);if(!sh)sh=ss.insertSheet(SHEET_PENGELUARAN);if(sh.getLastRow()===0)sh.getRange(1,1,1,4).setValues([['Timestamp','Tanggal','Deskripsi','Jumlah (Rp)']]).setFontWeight('bold');sh=ss.getSheetByName(SHEET_PENGATURAN);if(!sh)sh=ss.insertSheet(SHEET_PENGATURAN);if(sh.getLastRow()===0){sh.getRange(1,1,5,2).setValues([['Key','Value'],['NamaKelas','Kas Kelas 12.5'],['TanggalMulai',formatISO(new Date())],['IuranMingguan',5000],['SaldoAwal',0]]);sh.getRange(1,1,1,2).setFontWeight('bold');}ensureHistorySheet();SpreadsheetApp.flush();return'Setup selesai.';}
function ensureHistorySheet(){const ss=getSS();let sh=ss.getSheetByName(SHEET_HISTORY_ADMIN);if(!sh)sh=ss.insertSheet(SHEET_HISTORY_ADMIN);if(sh.getLastRow()===0)sh.getRange(1,1,1,6).setValues([['Timestamp','Tanggal','Nama','Jumlah (Rp)','Keterangan','Status']]).setFontWeight('bold');return sh;}
function backfillAdminHistory(){const history=ensureHistorySheet();if(history.getLastRow()>1)return'History sudah memiliki data.';const paymentSh=getSS().getSheetByName(SHEET_PEMBAYARAN);if(!paymentSh||paymentSh.getLastRow()<2)return'Tidak ada pembayaran lama untuk dipindahkan.';const rows=paymentSh.getDataRange().getValues().slice(1).filter(r=>r[1]&&r[3]);if(!rows.length)return'Tidak ada pembayaran lama untuk dipindahkan.';const output=rows.map(r=>[r[0]||new Date(),r[2]||new Date(),r[1],Number(r[3])||0,r[4]||'','Berhasil']);history.getRange(history.getLastRow()+1,1,output.length,6).setValues(output);return'History lama dipindahkan: '+output.length+' transaksi.';}

function formatISO(date){return Utilities.formatDate(new Date(date),Session.getScriptTimeZone()||'Asia/Jakarta','yyyy-MM-dd');}
function formatTanggalID(date){const bulan=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];const d=new Date(date);return d.getDate()+' '+bulan[d.getMonth()]+' '+d.getFullYear();}
function getSetting(key){const sh=getSS().getSheetByName(SHEET_PENGATURAN);const data=sh.getDataRange().getValues();for(let i=1;i<data.length;i++)if(data[i][0]===key)return data[i][1];return null;}
function setSetting(key,value){const sh=getSS().getSheetByName(SHEET_PENGATURAN);const data=sh.getDataRange().getValues();for(let i=1;i<data.length;i++)if(data[i][0]===key){sh.getRange(i+1,2).setValue(value);return true;}sh.appendRow([key,value]);return true;}
function getWeeksElapsed(){const startDate=new Date(getSetting('TanggalMulai'));const today=new Date();if(today<startDate)return 0;return Math.floor((today-startDate)/(7*24*60*60*1000))+1;}
function checkAdminPin(pin){return String(pin)===String(ADMIN_PIN);}
function getStudentList(){const sh=getSS().getSheetByName(SHEET_SISWA);const data=sh.getDataRange().getValues();const names=[];for(let i=1;i<data.length;i++)if(data[i][1])names.push(data[i][1]);return names;}
function getStudentStatus(nama){if(!nama)throw new Error('Nama wajib diisi.');const weeklyFee=Number(getSetting('IuranMingguan'));const weeksElapsed=getWeeksElapsed();const totalDue=weeksElapsed*weeklyFee;const data=getSS().getSheetByName(SHEET_PEMBAYARAN).getDataRange().getValues();let totalPaid=0;const history=[];for(let i=1;i<data.length;i++)if(data[i][1]===nama){const jumlah=Number(data[i][3])||0;totalPaid+=jumlah;history.push({tanggal:formatTanggalID(data[i][2]),tanggalRaw:new Date(data[i][2]).getTime(),jumlah:jumlah,keterangan:data[i][4]||''});}history.sort((a,b)=>b.tanggalRaw-a.tanggalRaw);const kurang=totalDue-totalPaid;return{nama,weeklyFee,weeksElapsed,totalDue,totalPaid,kurang,lunas:kurang<=0,history};}
function getStudentStatuses(){const weeklyFee=Number(getSetting('IuranMingguan'))||0;const weeksElapsed=getWeeksElapsed();const totalDuePerStudent=weeksElapsed*weeklyFee;const students=getStudentList();const payRows=getSS().getSheetByName(SHEET_PEMBAYARAN).getDataRange().getValues();const paidByName={};for(let i=1;i<payRows.length;i++){const nama=payRows[i][1];const jumlah=Number(payRows[i][3])||0;paidByName[nama]=(paidByName[nama]||0)+jumlah;}return students.map(nama=>{const totalPaid=paidByName[nama]||0;const kurang=totalDuePerStudent-totalPaid;return{nama,totalPaid,totalDue:totalDuePerStudent,kurang,lunas:kurang<=0};});}

function getAdminHistory(limit){const sh=ensureHistorySheet();const rows=sh.getDataRange().getValues();const history=[];for(let i=1;i<rows.length;i++){if(!rows[i][2])continue;history.push({timestampRaw:rows[i][0]?new Date(rows[i][0]).getTime():0,tanggal:formatTanggalID(rows[i][1]),nama:rows[i][2],jumlah:Number(rows[i][3])||0,keterangan:rows[i][4]||'',status:rows[i][5]||'Berhasil'});}history.sort((a,b)=>b.timestampRaw-a.timestampRaw);return history.slice(0,limit||15);}
function getAdminDashboard(pin){if(!checkAdminPin(pin))throw new Error('PIN salah.');ensureHistorySheet();const weeklyFee=Number(getSetting('IuranMingguan'));const weeksElapsed=getWeeksElapsed();const studentStatus=getStudentStatuses();const totalTerkumpul=studentStatus.reduce((a,s)=>a+s.totalPaid,0);const expRows=getSS().getSheetByName(SHEET_PENGELUARAN).getDataRange().getValues();let totalPengeluaran=0;const recentExpenses=[];for(let i=1;i<expRows.length;i++){const jumlah=Number(expRows[i][3])||0;totalPengeluaran+=jumlah;recentExpenses.push({tanggal:formatTanggalID(expRows[i][1]),deskripsi:expRows[i][2],jumlah});}recentExpenses.reverse();const saldoAwal=Number(getSetting('SaldoAwal'))||0;const saldoSaatIni=saldoAwal+totalTerkumpul-totalPengeluaran;return{namaKelas:getSetting('NamaKelas'),weeklyFee,weeksElapsed,tanggalMulai:formatTanggalID(getSetting('TanggalMulai')),tanggalMulaiISO:formatISO(new Date(getSetting('TanggalMulai'))),saldoAwal,saldoSaatIni,totalTerkumpul,totalPengeluaran,jumlahLunas:studentStatus.filter(s=>s.lunas).length,jumlahBelumLunas:studentStatus.filter(s=>!s.lunas).length,students:studentStatus,recentPayments:getAdminHistory(15),recentExpenses:recentExpenses.slice(0,15)};}

function addPayment(pin,nama,tanggalBayar,jumlah,keterangan){if(!checkAdminPin(pin))throw new Error('PIN salah.');if(!nama||!jumlah)throw new Error('Nama dan jumlah wajib diisi.');const amount=Number(jumlah);if(!isFinite(amount)||amount<=0)throw new Error('Jumlah pembayaran harus lebih dari 0.');const ss=getSS();const sh=ss.getSheetByName(SHEET_PEMBAYARAN);if(!sh)throw new Error('Sheet Pembayaran belum tersedia.');const now=new Date();const paymentDate=tanggalBayar?new Date(tanggalBayar+'T00:00:00'):new Date();sh.appendRow([now,nama,paymentDate,amount,keterangan||'']);const history=ensureHistorySheet();history.appendRow([now,paymentDate,nama,amount,keterangan||'','Berhasil']);SpreadsheetApp.flush();invalidateTransparencyCache();return'Pembayaran '+nama+' berhasil dicatat.';}
function addExpense(pin,tanggal,deskripsi,jumlah){if(!checkAdminPin(pin))throw new Error('PIN salah.');if(!deskripsi||!jumlah)throw new Error('Deskripsi dan jumlah wajib diisi.');const amount=Number(jumlah);if(!isFinite(amount)||amount<=0)throw new Error('Jumlah pengeluaran harus lebih dari 0.');const sh=getSS().getSheetByName(SHEET_PENGELUARAN);sh.appendRow([new Date(),tanggal?new Date(tanggal+'T00:00:00'):new Date(),deskripsi,amount]);invalidateTransparencyCache();return'Pengeluaran berhasil dicatat.';}
function updateSettings(pin,tanggalMulai,iuranMingguan,saldoAwal){if(!checkAdminPin(pin))throw new Error('PIN salah.');if(tanggalMulai)setSetting('TanggalMulai',tanggalMulai);if(iuranMingguan)setSetting('IuranMingguan',Number(iuranMingguan));if(saldoAwal!==null&&saldoAwal!==undefined&&saldoAwal!=='')setSetting('SaldoAwal',Number(saldoAwal));invalidateTransparencyCache();return'Pengaturan disimpan.';}
function addStudent(pin,nama){if(!checkAdminPin(pin))throw new Error('PIN salah.');nama=String(nama||'').trim();if(!nama)throw new Error('Nama wajib diisi.');const sh=getSS().getSheetByName(SHEET_SISWA);const data=sh.getDataRange().getValues();for(let i=1;i<data.length;i++)if(String(data[i][1]).trim().toLowerCase()===nama.toLowerCase())throw new Error('Nama siswa sudah ada.');sh.appendRow([Math.max(1,sh.getLastRow()),nama]);SpreadsheetApp.flush();invalidateTransparencyCache();return nama+' berhasil ditambahkan.';}

const TRANSPARENCY_CACHE_KEY='transparansi_data_v1';const TRANSPARENCY_CACHE_SECONDS=120;
function invalidateTransparencyCache(){try{CacheService.getScriptCache().remove(TRANSPARENCY_CACHE_KEY);}catch(err){console.error('invalidateTransparencyCache:',err);}}
function getTransparencyData(){const cache=CacheService.getScriptCache();const cached=cache.get(TRANSPARENCY_CACHE_KEY);if(cached)return JSON.parse(cached);const settingRows=getSS().getSheetByName(SHEET_PENGATURAN).getDataRange().getValues();const settings={};for(let i=1;i<settingRows.length;i++)settings[settingRows[i][0]]=settingRows[i][1];const saldoAwal=Number(settings['SaldoAwal'])||0;const payRows=getSS().getSheetByName(SHEET_PEMBAYARAN).getDataRange().getValues();const expRows=getSS().getSheetByName(SHEET_PENGELUARAN).getDataRange().getValues();const transactions=[];for(let i=1;i<payRows.length;i++)if(payRows[i][2])transactions.push({tanggalRaw:new Date(payRows[i][2]),jenis:'masuk',deskripsi:'Iuran kas — '+payRows[i][1],jumlah:Number(payRows[i][3])||0});for(let i=1;i<expRows.length;i++)if(expRows[i][1])transactions.push({tanggalRaw:new Date(expRows[i][1]),jenis:'keluar',deskripsi:expRows[i][2],jumlah:Number(expRows[i][3])||0});transactions.sort((a,b)=>a.tanggalRaw-b.tanggalRaw);let saldo=saldoAwal;const totalTransactions=transactions.map(t=>{saldo+=(t.jenis==='masuk'?t.jumlah:-t.jumlah);return{tanggal:formatTanggalID(t.tanggalRaw),tanggalRaw:t.tanggalRaw.getTime(),jenis:t.jenis,deskripsi:t.deskripsi,jumlah:t.jumlah,saldo};}).reverse();const totalPemasukan=transactions.filter(t=>t.jenis==='masuk').reduce((a,t)=>a+t.jumlah,0);const totalPengeluaran=transactions.filter(t=>t.jenis==='keluar').reduce((a,t)=>a+t.jumlah,0);const result={namaKelas:settings['NamaKelas'],saldoAwal,saldoAkhir:saldo,totalPemasukan,totalPengeluaran,transactions:totalTransactions,pemasukanHistory:totalTransactions.filter(t=>t.jenis==='masuk'),pengeluaranHistory:totalTransactions.filter(t=>t.jenis==='keluar')};try{cache.put(TRANSPARENCY_CACHE_KEY,JSON.stringify(result),TRANSPARENCY_CACHE_SECONDS);}catch(err){console.error('cache.put transparansi:',err);}return result;}
function getTransparencyDashboard(){const data=getTransparencyData();const weeksElapsed=getWeeksElapsed();const statuses=getStudentStatuses();const lunas=statuses.filter(s=>s.lunas).length;const belumLunas=statuses.filter(s=>!s.lunas).length;const chronological=data.transactions.slice().reverse();const daily={};const order=[];chronological.forEach(t=>{if(!daily[t.tanggal]){daily[t.tanggal]={in:0,out:0,saldo:t.saldo};order.push(t.tanggal);}const d=daily[t.tanggal];if(t.jenis==='masuk')d.in+=t.jumlah;else d.out+=t.jumlah;d.saldo=t.saldo;});const recentDays=order.slice(-14);return{saldo:data.saldoAkhir,totalMasuk:data.totalPemasukan,totalKeluar:data.totalPengeluaran,mingguBerjalan:weeksElapsed,lunas,belumLunas,labels:recentDays,balance:recentDays.map(k=>daily[k].saldo),income:recentDays.map(k=>daily[k].in),expense:recentDays.map(k=>daily[k].out),transactions:data.transactions,pemasukanHistory:data.pemasukanHistory,pengeluaranHistory:data.pengeluaranHistory};}
